steps:
# Build the container image
# docker build -t gcr.io/$PROJECT_ID/github.com/rwbutts/wordless_vue_dist:latest -f DockeDockerfilerfile 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/github.com/rwbutts/wordless_vue_dist:latest', '-f', 'Dockerfile.buildDistImage', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/github.com/rwbutts/wordless_vue_dist:latest']
images:
- gcr.io/$PROJECT_ID/github.com/rwbutts/wordless_vue_dist:latest
