FROM us-docker.pkg.dev/wordless-412000/miscellaneous/node16-minideb-base:latest as BASE

ARG TAG_VERSION='0.0.0'
ENV VUE_APP_VERSION=${TAG_VERSION}

WORKDIR /src

COPY ./package*.json ./
RUN npm install --legacy-peer-deps && npm install @vue/cli-service@4.5.19 --legacy-peer-deps

COPY . .
RUN npm run build

FROM scratch
WORKDIR /dist
COPY --from=BASE /src/dist .
